FROM python:3.9
MAINTAINER AlexanderFournier

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . /usr/src/app

ENV PYTHONPATH=/usr/src/app/python:$PYTHONPATH
ENV NEO4J_CENTRAL_USER=$neo4j_user
ENV NEO4J_CENTRAL_PASSWORD=$neo4j_password
ENV NEO4J_CENTRAL_URI=$neo4j_url

CMD ["python", "./main.py"]