FROM python:3.9
MAINTAINER AlexanderFournier

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . /usr/src/app

ENV PYTHONPATH=/usr/src/app/python:$PYTHONPATH
ENV OPEN_AI_API_KEY=$neo4j_user


CMD ["python", "./main.py"]